name: Build

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run all tests
        run: |
          coverage run -m unittest discover
      - name: Coverage Report
        run: |
          coverage report
